[metadata]
name = "alias"
description = "A channel to select from shell aliases"

[source]
command = "alias"
interactive = true
output = "{split:=:0}"

[preview]
command = "echo '{split:=:1..}'"

[ui]
layout = "portrait"

[ui.preview_panel]
size = 20
header = "{split:=:0}"
