tap "amazon/amazon", "ssh://git.amazon.com/pkg/HomebrewAmazon"
tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "weaveworks/tap"
brew "python@3.9"
brew "awscli"
brew "python@3.10", link: false
brew "cfn-lint"
brew "coreutils"
brew "exa"
brew "fzf"
brew "gnu-getopt"
brew "helm"
brew "htop"
brew "ipcalc"
brew "jq"
brew "parquet-tools"
brew "tcl-tk"
brew "python@3.8", link: false
brew "ripgrep"
brew "starship"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "amazon/amazon/isengard-cli"
brew "aws/tap/aws-sam-cli"
brew "weaveworks/tap/eksctl"
cask "background-music-pre"
cask "keepassxc"
cask "rectangle"
