git:
  paging:
    colorArg: always
    pager: delta --paging=never --side-by-side --line-numbers --syntax-theme "TokyoNight"
    # pager: delta --paging=never --side-by-side --line-numbers --syntax-theme "Catppuccin Mocha"
gui:
  # Tokyo night
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#7aa2f7"
    searchingActiveBorderColor:
      - "#9ece6a"
      - "bold"
    optionsTextColor:
      - "#bb9af7"
    selectedLineBgColor:
      - "#414868"
    inactiveViewSelectedLineBgColor:
      - "#414868"
      - "bold"
    cherryPickedCommitFgColor:
      - "#1a1b26"
    cherryPickedCommitBgColor:
      - "#7dcfff"
    # # Foreground color of marked base commit (for rebase)
    # markedBaseCommitFgColor:
    #   - blue
    # # Background color of marked base commit (for rebase)
    # markedBaseCommitBgColor:
    #   - yellow
    unstagedChangesColor:
      - "#f7768e"
    defaultFgColor:
      - "#c0caf5"
  # # Catppuccin mocha
  # authorColors:
  #   '*': '#b4befe'
  # theme:
  #   activeBorderColor:
  #     - '#89b4fa'
  #     - bold
  #   inactiveBorderColor:
  #     - '#a6adc8'
  #   optionsTextColor:
  #     - '#89b4fa'
  #   selectedLineBgColor:
  #     - '#313244'
  #   cherryPickedCommitBgColor:
  #     - '#45475a'
  #   cherryPickedCommitFgColor:
  #     - '#89b4fa'
  #   unstagedChangesColor:
  #     - '#f38ba8'
  #   defaultFgColor:
  #     - '#cdd6f4'
  #   searchingActiveBorderColor:
  #     - '#f9e2af'