gui:
  # Tokyo night
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#414868"
    optionsTextColor:
      - "#bb9af7"
  # # Catppuccin mocha
  # theme:
  #   activeBorderColor:
  #     - "#89b4fa"
  #     - bold
  #   inactiveBorderColor:
  #     - "#a6adc8"
  #   selectedLineBgColor:
  #     - "#313244"
  #   optionsTextColor:
  #     - "#89b4fa"