gui:
  # Catppuccin mocha
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    selectedLineBgColor:
      - "#585b70"
    optionsTextColor:
      - "#89b4fa"